# Generated by Django 6.0.7 on 2026-07-25 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('sector', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='BacktestPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_event_type', models.CharField(max_length=30)),
                ('relationship_type', models.CharField(max_length=20)),
                ('window_days', models.IntegerField()),
                ('sample_size', models.IntegerField()),
                ('hit_rate', models.FloatField(help_text='Fraction of historical instances where the predicted direction occurred')),
                ('avg_move_pct', models.FloatField()),
                ('predicted_direction', models.CharField(choices=[('up', 'Up'), ('down', 'Down')], max_length=10)),
                ('computed_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('trigger_event_type', 'relationship_type', 'window_days')},
            },
        ),
        migrations.CreateModel(
            name='NewsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=500)),
                ('event_type', models.CharField(choices=[('earnings_beat', 'Earnings beat'), ('earnings_miss', 'Earnings miss'), ('guidance_cut', 'Guidance cut'), ('guidance_raise', 'Guidance raise'), ('supply_disruption', 'Supply disruption'), ('regulatory', 'Regulatory action'), ('product_launch', 'Product launch'), ('lawsuit', 'Lawsuit'), ('other', 'Other')], max_length=30)),
                ('sentiment_score', models.FloatField(help_text='-1.0 (very negative) to 1.0 (very positive)')),
                ('magnitude', models.FloatField(help_text='0-1 estimated significance of the event')),
                ('published_at', models.DateTimeField()),
                ('source', models.CharField(blank=True, max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='market.company')),
            ],
        ),
        migrations.CreateModel(
            name='GeneratedChain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(max_length=20)),
                ('predicted_direction', models.CharField(max_length=10)),
                ('model_confidence', models.FloatField(help_text='Probability from the logistic regression model')),
                ('backtest_hit_rate', models.FloatField(blank=True, null=True)),
                ('explanation', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('affected_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affected_by_chains', to='market.company')),
                ('trigger_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_chains', to='market.newsevent')),
            ],
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('supplier', 'Supplier'), ('customer', 'Customer'), ('competitor', 'Competitor'), ('peer', 'Sector peer')], max_length=20)),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_from', to='market.company')),
                ('related_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_to', to='market.company')),
            ],
        ),
        migrations.AddIndex(
            model_name='newsevent',
            index=models.Index(fields=['company', 'published_at'], name='market_news_company_1a7b15_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='relationship',
            unique_together={('company', 'related_company', 'relationship_type')},
        ),
    ]
