# Generated by Django 6.0.7 on 2026-07-27 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_pipelinejob_pipelinelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelinejob',
            name='adapter_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='pipelinejob',
            name='upload_path',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
