# Generated by Django 6.0.7 on 2026-08-03 09:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_pipelinejob_adapter_id_pipelinejob_upload_path'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='backtestpattern',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='backtestpattern',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='backtest_patterns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='company',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='companies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='generatedchain',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generated_chains_list', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='newsevent',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='company',
            name='symbol',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='backtestpattern',
            unique_together={('user', 'trigger_event_type', 'relationship_type', 'window_days')},
        ),
        migrations.AlterUniqueTogether(
            name='company',
            unique_together={('user', 'symbol')},
        ),
    ]
