# Generated by Django 6.0.7 on 2026-08-03 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_alter_backtestpattern_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsevent',
            name='dedup_hash',
            field=models.CharField(blank=True, db_index=True, help_text='SHA-256 of ticker+headline+date, prevents duplicate ingestion', max_length=64, null=True, unique=True),
        ),
    ]
