# Generated by Django 6.0.7 on 2026-08-03 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_add_dedup_hash_to_newsevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedchain',
            name='source',
            field=models.CharField(choices=[('backtest', 'Historical Backtest'), ('live', 'Live Market Data')], default='backtest', max_length=20),
        ),
        migrations.AddField(
            model_name='newsevent',
            name='is_live',
            field=models.BooleanField(default=False, help_text='True if ingested via live scheduler, False if from historical CSV upload'),
        ),
    ]
