# Generated by Django 6.0.7 on 2026-08-03 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_add_source_and_is_live'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelinejob',
            name='job_type',
            field=models.CharField(choices=[('manual', 'Manual Batch'), ('scheduled', 'Scheduled Live Check')], default='manual', max_length=20),
        ),
    ]
