import { GitBranch, ArrowRight, ExternalLink } from 'lucide-react';
import { Card } from '@/shared/ui/Card';
import { InteractiveHoverButton } from '@/shared/ui/interactive-hover-button';

export function ChainsResults({ isActive, isCompleted }: { isActive: boolean, isCompleted: boolean }) {
  if (isActive) {
    return (
      <Card className="p-0 overflow-hidden mt-6">
        <div className="bg-surface-raised px-5 py-4 border-b border-border flex justify-between items-center">
          <div className="flex items-center gap-3">
            <GitBranch className="text-accent w-icon h-icon" />
            <h3 className="text-h3 text-text-primary">Generating Hypotheses</h3>
          </div>
        </div>
        <div className="p-10 text-center flex flex-col items-center">
          <div className="animate-pulse flex flex-col items-center">
            <div className="h-6 w-6 rounded-full border-2 border-accent border-t-transparent animate-spin mb-4" />
            <p className="text-body text-text-secondary">Synthesizing causal chains with explainable AI...</p>
          </div>
        </div>
      </Card>
    );
  }

  if (isCompleted) {
    return (
      <Card className="p-0 overflow-hidden mt-6 bg-positive-muted/5 border-positive/20">
        <div className="px-5 py-6 flex flex-col items-center text-center">
          <div className="w-12 h-12 rounded-full bg-positive-muted flex items-center justify-center mb-4 text-positive">
            <GitBranch className="w-6 h-6" />
          </div>
          <h3 className="text-h2 text-text-primary mb-2">Hypotheses Generated</h3>
          <p className="text-body text-text-secondary max-w-md mb-6">
            The pipeline has successfully completed. Causal chains have been generated by combining historical backtest hit rates, logistic regression confidence scoring, and plain-English synthesis.
          </p>
          <InteractiveHoverButton 
            onClick={() => window.location.href = '/chains'}
            text="Explore chains"
          />
        </div>
      </Card>
    );
  }

  return null;
}
